const DB='furusatoStandaloneDB', DOCS='documents', LOGS='logs', META='meta';
const $=id=>document.getElementById(id);
let state={documents:[],logs:[],manual:{}};
const yen=n=>n==null||!Number.isFinite(Number(n))?'—':Math.round(Number(n)).toLocaleString('ja-JP')+'円';
const num=v=>{const n=Number(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:0};
function addLog(msg,obj={}){const e={time:new Date().toISOString(),msg,...obj};state.logs.push(e);return e}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,3);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(DOCS))db.createObjectStore(DOCS,{keyPath:'id'});if(!db.objectStoreNames.contains(LOGS))db.createObjectStore(LOGS,{keyPath:'id',autoIncrement:true});if(!db.objectStoreNames.contains(META))db.createObjectStore(META,{keyPath:'key'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function tx(store,mode,fn){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,mode),s=t.objectStore(store);let out;try{out=fn(s)}catch(e){rej(e);return}t.oncomplete=()=>res(out);t.onerror=()=>rej(t.error)})}
const putDoc=d=>tx(DOCS,'readwrite',s=>s.put(d));
const allDocs=()=>tx(DOCS,'readonly',s=>new Promise((res,rej)=>{const r=s.getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}));
const putLog=e=>tx(LOGS,'readwrite',s=>s.add(e));
const allLogs=()=>tx(LOGS,'readonly',s=>new Promise((res,rej)=>{const r=s.getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}));
const getMeta=k=>tx(META,'readonly',s=>new Promise((res,rej)=>{const r=s.get(k);r.onsuccess=()=>res(r.result?.value);r.onerror=()=>rej(r.error)}));
const putMeta=(key,value)=>tx(META,'readwrite',s=>s.put({key,value}));
function makeId(d){return d.id||`${d.year||0}-${d.kind||d.type||'document'}-${d.month??'annual'}-${d.document||d.name||Math.random().toString(36).slice(2)}`}
function mapNested(d){
 const p=d.paymentItems||{}, q=d.deductionItems||{}, a=d.additionalPaymentItems||{}, w=d.workingRecord||{}, b=d.baseSalaryBreakdown||{}, sm=d.standardMonthlyRemuneration||{}, sb=d.standardBonusAmounts||{};
 const get=(obj,...keys)=>{for(const k of keys)if(obj[k]!=null)return obj[k];return null};
 const health=get(q,'健康保険料（基本','健康保険料（基本）'), healthSpecial=get(q,'健康保険料（特定','健康保険料（特定）');
 const out={...d}; out.kind=out.kind||out.type||'unknown'; out.name=out.name||out.document||`${out.year||''}-${out.month||''}`; out.payDate=out.payDate||out.payday||out.date||null; out.year=Number(out.year||String(out.payDate||'').slice(0,4)||0); out.month=out.month==null?null:Number(out.month);
 if(out.kind==='salary'){
  out.totalPayment=out.totalPayment??null; out.taxable=out.taxable??out.taxableAmount??null; out.nonTaxable=out.nonTaxable??out.nonTaxableAmount??null; out.additional=out.additional??out.additionalPaymentTotal??null; out.net=out.net??out.netPayment??null;
  out.employment=out.employment??get(q,'雇用保険料'); out.health=out.health??health; out.healthSpecial=out.healthSpecial??healthSpecial; out.care=out.care??get(q,'介護保険料'); out.pension=out.pension??get(q,'年金保険料'); out.incomeTax=out.incomeTax??get(q,'所得税'); out.residentTax=out.residentTax??get(q,'住民税');
  out.childSupport=out.childSupport??get(q,'子ども・子育て支援金'); out.deductions=out.deductions??out.totalDeduction; out.paymentItems=p; out.deductionItems=q; out.additionalPaymentItems=a; out.workingRecord=w; out.baseSalaryBreakdown=b; out.standardMonthlyRemuneration=sm;
 } else if(out.kind==='bonus'){
  out.amount=out.amount??out.bonusAmount??out.totalPayment??null; out.taxable=out.taxable??out.taxableGross??out.amount; out.totalPayment=out.totalPayment??out.amount; out.net=out.net??out.netPayment??null; out.employment=out.employment??get(q,'雇用保険料'); out.health=out.health??get(q,'健康保険料（基本','健康保険料（基本）'); out.healthSpecial=out.healthSpecial??get(q,'健康保険料（特定','健康保険料（特定）'); out.care=out.care??get(q,'介護保険料'); out.pension=out.pension??get(q,'年金保険料'); out.childSupport=out.childSupport??get(q,'子ども・子育て支援金'); out.incomeTax=out.incomeTax??get(q,'所得税'); out.deductions=out.deductions??out.totalDeduction; out.paymentItems=p; out.deductionItems=q; out.standardBonusAmounts=sb;
 }
 return out;
}
function normalizeDoc(raw,sourceName){
 const d=mapNested({...raw}); d.id=makeId(d); d.source=d.source||sourceName||'structured-json'; d.status=d.status||'parsed';
 d.social=d.social==null?deriveSocial(d):num(d.social); d.needsReview=Boolean(d.needsReview);
 if(d.kind==='salary'){d.missingFields=[]; if(d.year<=0)d.missingFields.push('year'); if(d.month==null)d.missingFields.push('month'); if(d.taxable==null)d.missingFields.push('taxableAmount'); if(d.totalPayment==null)d.missingFields.push('totalPayment'); d.needsReview=d.missingFields.length>0;}
 return d;
}
function deriveSocial(d){return ['employment','health','healthSpecial','care','childSupport','pension'].map(k=>num(d[k])).reduce((a,b)=>a+b,0)}
async function importJsonText(text,sourceName='ChatGPT JSON'){
 const parsed=JSON.parse(text); const list=Array.isArray(parsed)?parsed:(Array.isArray(parsed.documents)?parsed.documents:[]); if(!list.length)throw new Error('documents配列がありません');
 let added=0,updated=0; for(const raw of list){const d=normalizeDoc(raw,sourceName);const old=state.documents.find(x=>x.id===d.id);await putDoc(d);old?updated++:added++}
 const log=addLog('データ反映',{source:sourceName,count:list.length,added,updated});await putLog(log);state.documents=await allDocs();state.logs=await allLogs();render();showMessage(`反映完了：${added}件追加、${updated}件更新。DB保存済み`,'ok');
}
function lifeDeduction(premium,type,year,under23=false){const x=num(premium);if(!x)return 0;if(type==='new')return x<=20000?x:x<=40000?x/2+10000:x<=80000?x/4+20000:40000;if(type==='newLife'&&year>=2026&&under23)return x<=30000?x:x<=60000?x/2+15000:x<=120000?x/4+30000:60000;if(type==='old')return x<=25000?x:x<=50000?x/2+12500:x<=100000?x/4+25000:50000;return 0}
function calcLife(m,year){
 const under23=Boolean(m.under23Dependent&&year>=2026); const nl=num(m.newLife), ol=num(m.oldLife), np=num(m.newPension), op=num(m.oldPension), med=num(m.medical);
 const general=ol>60000?lifeDeduction(ol,'old',year):Math.min(40000,lifeDeduction(nl,'newLife',year,under23)+lifeDeduction(ol,'old',year));
 const pension=op>60000?lifeDeduction(op,'old',year):Math.min(40000,lifeDeduction(np,'new',year)+lifeDeduction(op,'old',year));
 const medical=Math.min(40000,lifeDeduction(med,'new',year)); const total=Math.min(120000,general+pension+medical);
 return {general,pension,medical,total,raw:{newLife:nl,oldLife:ol,medical:med,newPension:np,oldPension:op}};
}
function earthquakeDeduction(m){const e=num(m.earthquake), old=num(m.oldLongTermDamage); return Math.min(50000,e)+Math.min(15000,old)}
function manualFor(year){return state.manual[String(year)]||{newLife:0,oldLife:0,medical:0,newPension:0,oldPension:0,earthquake:0,oldLongTermDamage:0,ideco:0,nationalPension:0,daughterNationalPension:0,daughterPensionEligible:true,temporary:0,temporaryTaxable:true,under23Dependent:false,note:''}}
function salaryDeduction(gross){if(gross<=1900000)return 650000;if(gross<=3600000)return gross*.3+80000;if(gross<=6600000)return gross*.2+440000;if(gross<=8500000)return gross*.1+1100000;return 1950000}
function basicDeduction(income){if(income<=1320000)return 950000;if(income<=3360000)return 880000;if(income<=4890000)return 680000;if(income<=6550000)return 630000;if(income<=23500000)return 580000;return income<=24000000?480000:income<=24500000?320000:income<=25000000?160000:0}
function incomeTaxRate(t){if(t<=1949000)return .05;if(t<=3299000)return .10;if(t<=6949000)return .20;if(t<=8999000)return .23;if(t<=17999000)return .33;if(t<=39999000)return .40;return .45}
function forecastSalaryTaxable(docs,year){const sal=docs.filter(d=>d.kind==='salary'&&d.year===year&&!d.needsReview&&d.taxable!=null).sort((a,b)=>a.month-b.month),by=new Map(sal.map(d=>[d.month,d])),est={};for(let m=1;m<=12;m++){if(by.has(m)){est[m]={value:num(by.get(m).taxable),source:'actual'};continue}let xs=[];if(m===5)xs=[by.get(4)?.taxable];else if(m===6)xs=[by.get(4)?.taxable,by.get(5)?.taxable];else if(m>=7&&m<=11)xs=[by.get(m-3)?.taxable,by.get(m-2)?.taxable,by.get(m-1)?.taxable];else if(m===12)xs=[by.get(9)?.taxable,by.get(10)?.taxable,by.get(11)?.taxable];xs=xs.filter(v=>v!=null).map(num);if(xs.length===((m===5)?1:(m===6?2:3)))est[m]={value:xs.reduce((a,b)=>a+b,0)/xs.length,source:'forecast'}}return {sal,est}}
function bonusForecast(docs,year){const bs=docs.filter(d=>d.kind==='bonus'&&d.year===year&&!d.needsReview);const actual=bs.reduce((s,d)=>s+num(d.taxable??d.amount),0);const winter=bs.find(d=>d.month===12);const prior=docs.filter(d=>d.kind==='bonus'&&d.year===year-1&&d.month===12&&!d.needsReview).reduce((s,d)=>Math.max(s,num(d.taxable??d.amount)),0);const forecast=!winter?(prior||0):0;return {bs,actual,winter,prior,forecast,source:winter?'actual':prior?'prior-year':'none'}}
function forecast(docs,year){const sf=forecastSalaryTaxable(docs,year);if(!sf.sal.length)return null;const yearSalary=Object.values(sf.est).reduce((s,x)=>s+x.value,0);const actualMonths=sf.sal.filter(d=>d.month<=11);const dec=sf.est[12];const salarySocial=actualMonths.reduce((s,d)=>s+num(d.social),0)+(sf.est[12]?.source==='actual'?num(sf.sal.find(d=>d.month===12)?.social):actualMonths.length?actualMonths.reduce((s,d)=>s+num(d.social),0)/actualMonths.length:0);const bf=bonusForecast(docs,year);const bonusTotal=bf.actual+bf.forecast;const manual=manualFor(year);const tempTaxable=manual.temporaryTaxable?num(manual.temporary):0;const totalIncome=yearSalary+bonusTotal+tempTaxable;const life=calcLife(manual,year),earth=earthquakeDeduction(manual);const daughter=manual.daughterPensionEligible?num(manual.daughterNationalPension):0;const manualSocial=num(manual.nationalPension)+daughter;const manualDed=num(manual.ideco)+life.total+earth;const salaryDed=salaryDeduction(yearSalary);const salaryIncome=Math.max(0,yearSalary-salaryDed);const basic=basicDeduction(salaryIncome);const totalSocial=salarySocial+manualSocial;const taxable=Math.max(0,Math.floor((totalIncome-salaryDed-totalSocial-basic-manualDed)/1000)*1000);const rate=incomeTaxRate(taxable);const cap=Math.floor(2000+(taxable*.10*.20)/(0.90-rate*1.021));return {yearSalary,actualMonths:actualMonths.length,dec:dec?.value,decSource:dec?.source,bonusTotal,bonusSource:bf.source,manual,life,earth,daughter,manualSocial,manualDed,salaryDed,basic,totalSocial,taxable,cap}}
function showMessage(msg,cls='ok'){const e=$('actionMessage');e.textContent=msg;e.className='message '+cls;setTimeout(()=>{if(e.textContent===msg)e.textContent=''},4000)}
function renderManual(){const years=[...new Set([...state.documents.map(d=>d.year),...Object.keys(state.manual).map(Number),2025,2024])].filter(Boolean).sort((a,b)=>b-a);const y=num($('manualYear')?.value)||years[0]||2025;if(!$('manualYear'))return; $('manualYear').innerHTML=years.map(v=>`<option value="${v}">${v}年</option>`).join('');$('manualYear').value=String(y);const m=manualFor(y);for(const id of ['newLife','oldLife','medical','newPension','oldPension','earthquake','oldLongTermDamage','ideco','nationalPension','daughterNationalPension','temporary'])$(id).value=m[id]??0;$('daughterPensionEligible').checked=m.daughterPensionEligible!==false;$('temporaryTaxable').checked=m.temporaryTaxable!==false;$('under23Dependent').checked=Boolean(m.under23Dependent);$('manualNote').value=m.note||'';updateManualCalc()}
function updateManualCalc(){const y=num($('manualYear').value),m={};for(const id of ['newLife','oldLife','medical','newPension','oldPension','earthquake','oldLongTermDamage','ideco','nationalPension','daughterNationalPension','temporary'])m[id]=num($(id).value);m.daughterPensionEligible=$('daughterPensionEligible').checked;m.temporaryTaxable=$('temporaryTaxable').checked;m.under23Dependent=$('under23Dependent').checked;const l=calcLife(m,y),e=earthquakeDeduction(m);$('lifeBreakdown').innerHTML=`<div>一般生命保険：${yen(l.general)}</div><div>個人年金：${yen(l.pension)}</div><div>介護医療：${yen(l.medical)}</div><strong>生命保険料控除 合計：${yen(l.total)}（上限120,000円）</strong>`;$('earthquakeResult').textContent=`地震保険料控除：${yen(e)}`;$('manualSummary').innerHTML=`iDeCo・小規模企業共済等：${yen(m.ideco)} ／ 国民年金本人：${yen(m.nationalPension)} ／ 娘の国民年金：${m.daughterPensionEligible?'含める':'含めない'} ${yen(m.daughterNationalPension)} ／ 給与調整：${yen(m.temporary)} ${m.temporaryTaxable?'課税':'非課税'}`;}
async function saveManual(){const y=num($('manualYear').value),m={};for(const id of ['newLife','oldLife','medical','newPension','oldPension','earthquake','oldLongTermDamage','ideco','nationalPension','daughterNationalPension','temporary'])m[id]=num($(id).value);m.daughterPensionEligible=$('daughterPensionEligible').checked;m.temporaryTaxable=$('temporaryTaxable').checked;m.under23Dependent=$('under23Dependent').checked;m.note=$('manualNote').value;state.manual[String(y)]=m;await putMeta('manual',state.manual);const log=addLog('手動入力保存',{year:y,manual:m});await putLog(log);state.logs=await allLogs();render();showMessage(`${y}年の手動入力を保存しました。計算にも反映済み。`,'ok')}
function render(){const docs=state.documents.slice().sort((a,b)=>(a.year||0)-(b.year||0)||(a.month||0)-(b.month||0));const years=[...new Set(docs.map(d=>d.year).filter(Boolean))].sort((a,b)=>b-a);$('status').innerHTML=`<div class="grid"><div class="metric"><span>保存データ</span><b>${docs.length}</b></div><div class="metric"><span>給与</span><b>${docs.filter(d=>d.kind==='salary').length}</b></div><div class="metric"><span>賞与</span><b>${docs.filter(d=>d.kind==='bonus').length}</b></div><div class="metric"><span>源泉徴収票</span><b>${docs.filter(d=>d.kind==='withholding').length}</b></div><div class="metric"><span>確認必要</span><b>${docs.filter(d=>d.needsReview).length}</b></div></div>`;
 $('documents').innerHTML=docs.map(d=>`<details class="file"><summary><b>${d.year||'—'}/${d.month?String(d.month).padStart(2,'0')+' ':''}${d.name||d.document||'資料'}</b>　${d.needsReview?'<span class="warn">確認必要</span>':'<span class="ok">保存済み</span>'}</summary><div class="rawgrid"><div>種類</div><div>${d.kind}</div><div>課税対象額</div><div>${yen(d.taxable??d.taxableAmount)}</div><div>支給合計</div><div>${yen(d.totalPayment)}</div><div>非課税額</div><div>${yen(d.nonTaxable??d.nonTaxableAmount)}</div><div>社会保険料</div><div>${yen(d.social)}</div><div>所得税</div><div>${yen(d.incomeTax??d.withholdingTax)}</div><div>住民税</div><div>${yen(d.residentTax)}</div><div>追加支給</div><div>${yen(d.additional??d.additionalPaymentTotal)}</div></div><details><summary>読み取った全項目をJSONで確認</summary><pre>${escapeHtml(JSON.stringify(d,null,2))}</pre></details></details>`).join('')||'<p>まだデータがありません。</p>';
 const selectedYear=num($('calcYear')?.value)||years[0]||2025;if($('calcYear')){$('calcYear').innerHTML=[...new Set([...years,2025,2024])].sort((a,b)=>b-a).map(y=>`<option value="${y}">${y}年</option>`).join('');$('calcYear').value=String(selectedYear)}const f=forecast(docs,selectedYear);$('summary').innerHTML=f?`<div class="grid"><div class="metric"><span>給与年間</span><b>${yen(f.yearSalary)}</b></div><div class="metric"><span>12月給与</span><b>${yen(f.dec)}</b></div><div class="metric"><span>賞与</span><b>${yen(f.bonusTotal)}</b></div><div class="metric"><span>社会保険料</span><b>${yen(f.totalSocial)}</b></div><div class="metric"><span>生命保険料控除</span><b>${yen(f.life.total)}</b></div><div class="metric"><span>iDeCo等</span><b>${yen(f.manualDed-f.life.total-f.earth)}</b></div><div class="metric"><span>比較用課税所得</span><b>${yen(f.taxable)}</b></div><div class="metric"><span>上限概算</span><b>${yen(f.cap)}</b></div></div><p class="small">源泉徴収票は予測計算には使用していません。実績がそろった後の比較・最終計算用として保存します。</p>`:'<p>この年度の給与データがありません。</p>';
 $('details').innerHTML=docs.map(d=>`<div class="file"><b>${d.name||d.document||'資料'}</b><br>保存項目：${Object.keys(d).length}項目　／　計算使用：${d.kind==='salary'?'課税対象額・社会保険料・実績月':'賞与額・社会保険料等（計算段階に応じて）'}${d.kind==='withholding'?'／予測には不使用・比較用':''}</div>`).join('');renderManual();}
function escapeHtml(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
$('reflectJson').onclick=async()=>{try{await importJsonText($('jsonInput').value);$('jsonInput').value=''}catch(e){showMessage('反映できません：'+e.message,'error')}};
$('copyPrompt').onclick=async()=>{const prompt='ふるさと納税アプリへ反映して。Libraryの最新資料と既存データを比較し、重複を除外。給与明細・賞与明細・源泉徴収票は原文にある項目を省略せず、{"version":1,"documents":[...]}で全項目を返してください。源泉徴収票は予測に使わず、実績後の比較用に保存してください。';await navigator.clipboard.writeText(prompt);showMessage('ChatGPTへの依頼文をコピーしました。','ok')};
$('saveManual').onclick=saveManual;$('manualYear').onchange=renderManual;document.querySelectorAll('#manualForm input').forEach(e=>e.addEventListener('input',updateManualCalc));document.querySelectorAll('#manualForm input[type=checkbox]').forEach(e=>e.addEventListener('change',updateManualCalc));$('calcYear').onchange=render;
$('exportDb').onclick=()=>download('furusato_db.json',JSON.stringify({version:1,documents:state.documents,manual:state.manual},null,2));$('exportLog').onclick=()=>download('furusato_debug.txt',state.logs.map(x=>JSON.stringify(x)).join('\n'));$('clearDb').onclick=async()=>{if(confirm('保存データと手動入力を消去しますか？')){const db=await openDB();await new Promise((res,rej)=>{const t=db.transaction([DOCS,LOGS,META],'readwrite');t.objectStore(DOCS).clear();t.objectStore(LOGS).clear();t.objectStore(META).clear();t.oncomplete=res;t.onerror=()=>rej(t.error)});state={documents:[],logs:[],manual:{}};render();showMessage('消去しました','ok')}};
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
state.documents=await allDocs();state.logs=await allLogs();state.manual=await getMeta('manual')||{};
// Migrate old imported records such as type:'salary' / nested 2024 JSON so they stop showing as unknown.
for(const d of [...state.documents]){const n=normalizeDoc(d,'migrated');if(JSON.stringify(n)!==JSON.stringify(d))await putDoc(n)}
state.documents=await allDocs();render();
