const DB='furusatoConsumptionDB', STORE='records', META='meta', HISTORY='history';
const $=id=>document.getElementById(id); const yen=n=>Number.isFinite(Number(n))?Math.round(Number(n)).toLocaleString('ja-JP')+'円':'—';
let db;
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'});if(!d.objectStoreNames.contains(META))d.createObjectStore(META,{keyPath:'key'});if(!d.objectStoreNames.contains(HISTORY))d.createObjectStore(HISTORY,{keyPath:'id',autoIncrement:true})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function tx(store,mode,fn){return new Promise((res,rej)=>{const t=db.transaction(store,mode),s=t.objectStore(store);let out;try{out=fn(s)}catch(e){rej(e);return}t.oncomplete=()=>res(out);t.onerror=()=>rej(t.error)})}
const all=(s)=>tx(s,'readonly',st=>new Promise((r,j)=>{const q=st.getAll();q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)}));
const put=(s,v)=>tx(s,'readwrite',st=>st.put(v)); const delAll=s=>tx(s,'readwrite',st=>st.clear());
const getMeta=k=>tx(META,'readonly',s=>new Promise((r,j)=>{const q=s.get(k);q.onsuccess=()=>r(q.result?.value);q.onerror=()=>j(q.error)})); const putMeta=(k,v)=>put(META,{key:k,value:v});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function today(){return new Date().toISOString().slice(0,10)}
function monthStart(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10)}
function initDates(){if(!$('mailFrom').value)$('mailFrom').value=monthStart();if(!$('mailTo').value)$('mailTo').value=today();if(!$('listFrom').value)$('listFrom').value=monthStart();if(!$('listTo').value)$('listTo').value=today()}
function classify(m){const t=[m.subject,m.from,m.bodyText,m.snippet].filter(Boolean).join(' ');if(/ふるさと納税|寄附|返礼品|ふるさとチョイス|さとふる|ふるなび|楽天ふるさと納税|ふるさと納税返礼品/i.test(t))return 'ふるさと納税';if(/amazon|楽天|yahoo|paypay|shopping|購入|注文|決済/i.test(t))return '買い物';return 'その他'}
function extractAmount(m){const t=[m.subject,m.bodyText,m.snippet].filter(Boolean).join(' ');const ms=[...t.matchAll(/(?:合計|お支払(?:い)?金額|支払金額|ご請求額|請求額|決済金額|寄附金額)[^0-9]{0,12}([0-9][0-9,]{2,})\s*円?/g)];if(ms.length)return Number(ms[0][1].replace(/,/g,''));const all=[...t.matchAll(/([0-9][0-9,]{2,})\s*円/g)].map(x=>Number(x[1].replace(/,/g,''))).filter(x=>x>500);return all.length?Math.max(...all):null}
function extractTitle(m){const s=String(m.subject||'').trim();return s||String(m.snippet||m.bodyText||'').trim().slice(0,80)||'メールからの消費候補'}
function toRecord(m){const id=String(m.id||m.messageId||m.uid||`${m.date}-${m.subject}`);return{id,source:'Yahoo Mail',messageId:id,date:(m.date||'').slice(0,10),receivedAt:m.date||null,from:m.from||'',title:extractTitle(m),amount:extractAmount(m),category:classify(m),status:'candidate',rawText:$('saveRaw').checked?String(m.bodyText||m.snippet||''):null,updatedAt:new Date().toISOString()}}
async function getHistory(){return all(HISTORY)}
async function render(){const rs=await all(STORE);const f=$('listFrom').value,t=$('listTo').value;const xs=rs.filter(x=>(!f||x.date>=f)&&(!t||x.date<=t)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const total=xs.reduce((a,x)=>a+(Number(x.amount)||0),0);$('summary').innerHTML=`<div class="metric"><span>候補件数</span><b>${xs.length}件</b></div><div class="metric"><span>金額合計</span><b>${yen(total)}</b></div><div class="metric"><span>ふるさと納税候補</span><b>${xs.filter(x=>x.category==='ふるさと納税').length}件</b></div>`;$('records').innerHTML=xs.length?xs.map(x=>`<article class="record"><div class="record-head"><div><div class="record-title">${esc(x.title)}</div><span class="badge">${esc(x.category)}</span><span class="badge">${esc(x.date||'日付不明')}</span></div><div class="amount">${x.amount==null?'金額未取得':yen(x.amount)}</div></div><div class="small">${esc(x.from)}${x.messageId?` ／ ID: ${esc(x.messageId)}`:''}</div></article>`).join(''):'<p class="note">まだ消費データがありません。</p>';const h=await getHistory();const last=h.filter(x=>x.success).sort((a,b)=>String(b.to).localeCompare(String(a.to)))[0];$('throughDate').textContent=last?.to||'—';$('mailStatus').textContent=last?'連携済み':'未連携';$('historyList').innerHTML=h.length?h.sort((a,b)=>b.id-a.id).map(x=>`<div class="history"><strong>${esc(x.from||'')} ～ ${esc(x.to||'')}</strong><div>${x.success?'読み取り成功':'失敗'}：${x.count||0}件 ／ ${esc(x.at||'')}</div>${x.error?`<div class="error">${esc(x.error)}</div>`:''}</div>`).join(''):'<p class="note">履歴はまだありません。</p>'}
async function connectYahoo(){const base=localStorage.getItem('furusatoYahooBridge')||'';if(!base){alert('まずYahooメール中継APIのURLを設定します。設定値はこの端末だけに保存します。');const u=prompt('中継APIのベースURL（例：https://your-server.example.com）');if(!u)return;localStorage.setItem('furusatoYahooBridge',u.replace(/\/$/,''))}const bridge=localStorage.getItem('furusatoYahooBridge');window.location.href=bridge+'/auth/start?return_to='+encodeURIComponent(location.href)}
async function readYahoo(){const bridge=localStorage.getItem('furusatoYahooBridge');if(!bridge){$('mailMessage').textContent='中継APIが未設定です。Yahoo!メールを連携を押して設定してください。';$('mailMessage').className='message error';return}const from=$('mailFrom').value,to=$('mailTo').value;if(!from||!to||from>to){$('mailMessage').textContent='読み取り期間を正しく指定してください。';$('mailMessage').className='message error';return}const history=await getHistory();const successful=history.filter(x=>x.success);const latest=successful.sort((a,b)=>String(b.to).localeCompare(String(a.to)))[0];let effectiveFrom=from;if($('autoSkip').checked&&latest&&latest.to>=from&&latest.to<to){const d=new Date(latest.to+'T00:00:00');d.setDate(d.getDate()+1);effectiveFrom=d.toISOString().slice(0,10)}else if($('autoSkip').checked&&latest&&latest.to>=to){$('mailMessage').textContent=`${to}まで取得済みのため、今回は再取得しません。履歴リセットで再取得できます。`;$('mailMessage').className='message ok';return}$('mailMessage').textContent=`読み取り中… ${effectiveFrom} ～ ${to}`;$('mailMessage').className='message';try{const q=new URLSearchParams({from:effectiveFrom,to,query:$('mailQuery').value||''});const r=await fetch(`${bridge}/mail/messages?${q}`);if(!r.ok)throw new Error(await r.text());const data=await r.json();const existing=new Set((await all(STORE)).map(x=>x.messageId));let added=0;for(const m of (data.messages||[])){const rec=toRecord(m);if(existing.has(rec.messageId))continue;await put(STORE,rec);added++}await put(HISTORY,{from:effectiveFrom,to,success:true,count:added,at:new Date().toISOString(),messageIds:(data.messages||[]).map(m=>String(m.id||m.messageId||m.uid))});$('mailMessage').textContent=`読み取り成功：${added}件。${to}までの成功履歴を保存しました。`;$('mailMessage').className='message ok';await render()}catch(e){await put(HISTORY,{from:effectiveFrom,to,success:false,count:0,at:new Date().toISOString(),error:e.message});$('mailMessage').textContent='読み取り失敗：'+e.message;$('mailMessage').className='message error';await render()}}
async function resetHistory(){if(!confirm('読み取り履歴を全消去して、同じ期間を再取得できる状態にします。消費データ自体は消しません。よろしいですか？'))return;await delAll(HISTORY);$('mailMessage').textContent='履歴をリセットしました。消費データは保持しています。';$('mailMessage').className='message ok';await render()}
function tabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tabpage').forEach(x=>x.hidden=x.id!==`tab-${b.dataset.tab}`)})}
$('connectYahoo').onclick=connectYahoo;$('readYahoo').onclick=readYahoo;$('resetHistory').onclick=resetHistory;$('refreshList').onclick=render;
(async()=>{await openDB();initDates();tabs();const p=new URLSearchParams(location.search);if(p.get('yahoo')==='connected'){$('mailMessage').textContent='Yahoo!メールの連携が完了しました。';$('mailMessage').className='message ok'}await render()})();
